services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Toumoro\TmMigration\:
    resource: '../Classes/*'

  Toumoro\TmMigration\Command\FixDatabaseErrorsCommand:
    tags:
      - name: console.command
        command: 'tmupgrade:fixdatabaseerrors'
        description: 'Fix database updateschema errors.'

  Toumoro\TmMigration\Command\ExportCtypeListTypeCommand:
    tags:
      - name: console.command
        command: 'tmexport:types'
        description: 'Export CTypes and List Types to JSON or CSV.'

  Toumoro\TmMigration\Command\RunSqlScriptCommand:
    tags:
      - name: console.command
        command: 'tmupgrade:importsql'
        description: 'Run custom SQL scripts.'

  Toumoro\TmMigration\Command\SeperateSyshistoryFromSyslogCommand:
    tags:
      - name: console.command
        command: 'tmupgrade:sepearate-syshistory-from-syslog'
        description: 'This command execute an SQL script that seperates sys_history from sys_log table [options] -d days -l limit.'

  Toumoro\TmMigration\Command\UpgradeWizardRunCommand:
    tags:
      - name: console.command
        command: 'tmupgrade:run'
        description: 'This command runs upgrade wizards.'